### ISSUE TITLE
您好，能否提供单张图片的推理脚本

### ISSUE THREAD

**Issue by guanba666** [SJingjia/PlaneRecTR#1]

**Comment by SJingjia** [comment]
十分抱歉才看到，我忙完这周会尽快上传，也可以参考https://github.com/facebookresearch/Mask2Former/blob/main/demo/demo.py， 简单修改一下config加载（add_maskformer2_config->add_PlaneRecTR_config）应该就可以跑起来单张inference

**Comment by SJingjia** [comment]
已上传
