### ISSUE TITLE
inference on single image?

### ISSUE THREAD

**Issue by aroop** [SJingjia/PlaneRecTR#2]
Hi, Thank you for the great work. Would you please share the inference script of PlaneRecTR? I would like to test your work on my own image. Thanks!

**Comment by SJingjia** [comment]
Hi, thanks for your interest in our work. I'll upload the inference demo as soon, and If you need it urgently, you can also refer to https://github.com/facebookresearch/Mask2Former/blob/main/demo/demo.py, https://github.com/facebookresearch/detectron2/blob/master/demo/demo.py

**Comment by IresAtLetink** [comment]
Hi @SJingjia - thank you for you work!

I've tried to setup a script to setup inference based on the demo files with mixed result. Using the default config and the r50 pretrained data I'm getting a tensor size error on the inferred_seg_depth calculation. I'm having difficulty debugging - any pointers for me where to look?

**Comment by SJingjia** [comment]
Hi @IresAtLetink  @aroop  I've uploaded an inference demo you can try it out

**Comment by aroop** [comment]
Thanks @SJingjia 

Verified that demo is working
