### ISSUE TITLE
the meaning of loss_Q

### ISSUE THREAD

**Issue by lqzhao** [SJingjia/PlaneRecTR#7]
Hello, I found `self.losses` contains ['labels', 'masks', 'plane_depths', 'params', 'Q', 'plane_depths'], I don't understand the meaning of loss_Q. Did the paper mention this loss? Thanks for your effort.

**Comment by SJingjia** [comment]
Plane parameter loss is in a similar form to previous works "PlaneTR". loss_Q is the third term.
![image](https://github.com/SJingjia/PlaneRecTR/assets/28842290/d19a7800-44e5-4115-bbd4-305e86949b68)
